---
title: "ch02"
author: "Sasha Han"
date: "2/7/2021"
output: github_document
---

```{r setup, echo = F, warning = F, message = F}
library(tidyverse)
library(rethinking)
```

**2E1.** (4) <br>
**2E2.** (3) <br>
**2E3.** (1) <br>
**2E4.** When we toss the globe, 70% of the time we will have water. <br>
**2M1.** 

```{r}
gridapprox_fun <- function(w, toss) {
  grid_size = 1000
  grid_p = seq(0, 1, length.out = grid_size)
  prior = rep(1, grid_size) ## uniform prior
  likelihood = dbinom(w, toss, grid_p)
  posterior_unstd = likelihood * prior
  posterior = posterior_unstd/sum(posterior_unstd)
  samples = sample(grid_p, size = 1e4,  replace = T, prob=posterior)
}

w3 <- gridapprox_fun(w = 3, toss = 3)
w3l1 <- gridapprox_fun(w = 3, toss = 4)
w5l2 <- gridapprox_fun(w = 5, toss = 7)

#+ fig.height = 4, fig.width = 4
dens(w3, xlab = "Prob.", xlim = c(0, 1))
dens(w3l1, add = T, col = "orange")
dens(w5l2, add = T, col = "blue")
legend("top", col=c("black", "orange", "blue"), bty = "n", lty = 1,
       legend = c("WWW", "WWWL", "LWWLWWW"))
```

**2M2.** 
```{r, fig.height = 4, fig.width = 4}
gridapprox_fun2 <- function(w, toss) {
  grid_size = 1000
  grid_p = seq(0, 1, length.out = grid_size)
  ## zero when p<0.5 and uniform when p>=0.5
  prior = c(rep(0, sum(grid_p<0.5)), rep(1, sum(grid_p>=0.5))) 
  likelihood = dbinom(w, toss, grid_p)
  posterior_unstd = likelihood * prior
  posterior = posterior_unstd/sum(posterior_unstd)
  samples = sample(grid_p, size = 1e4,  replace = T, prob=posterior)
}
w3 <- gridapprox_fun2(w = 3, toss = 3)
w3l1 <- gridapprox_fun2(w = 3, toss = 4)
w5l2 <- gridapprox_fun2(w = 5, toss = 7)
#+ fig.height = 4, fig.width = 4
dens(w3, xlab = "Prob.", xlim = c(0, 1))
dens(w3l1, add = T, col = "orange")
dens(w5l2, add = T, col = "blue")
legend("top", col=c("black", "orange", "blue"), bty = "n", lty = 1,
       legend = c("WWW", "WWWL", "LWWLWWW"))
```

**2M3.** $P(E|L)=\dfrac{P(L|E)P(E)}{P(L|E)P(E) + P(L|M)P(M)} =
\dfrac{0.3 \times 0.5}{0.3 \times 0.5 + 1 \times 0.5}=0.23$ <br>